### ISSUE TITLE
Bugsnag connection issues in github actions

### ISSUE THREAD

**Issue by marcellino-ornelas** [bugsnag/bugsnag-build-reporter-node#24]
### Describe the bug
Im trying to integrate https://github.com/lhansford/bugsnag-report-build-action on my Github enterprise server but running into the follow issue:

```
[bugsnag-build-reporter]   Error: connect ETIMEDOUT 35.227.235.70:443, Error: connect ENETUNREACH 2600:1901:0:e603:::443 - Local (:::0)
/mnt/github_actions_runner/_work/_actions/lhansford/bugsnag-report-build-action/v1.3.0/dist/index.js:2105
      reject(new Error('bugsnag-build-reporter failed'))
```

I took a look at the source code and all it does it call your library so decided to make this issue here and not in the action library. Any ideas why this would be happening? Heres my yaml file

```yaml
- name: Bugsnag report build
        uses: lhansford/bugsnag-report-build-action@v1.3.0
        with:
          apiKey:  ${{ secrets.BUGSNAG_API_TOKEN }}
          appVersion: ${{ github.sha }}
          failCiIfError: true
          sourceControlProvider: github-enterprise
          sourceControlRepository: https://myorg-github.com/org/repo
        env:
          BUGSNAG_TIMEOUT: 60000
```

we do used self hosted workers but we have verified that we can reach the bugsnag hosts

```
curl -v https://build.bugsnag.com/
{"type":"about:blank","title":"Method Not Allowed","status":405,"detail":"Method 'GET' is not supported.","instance":"/"}
```

### Environment
* Node version: `16.20.x`
* NPM version: `8.19.4`

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>
